# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_pestana_producto_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestana',
            name='producto_pro',
        ),
    ]
