# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0006_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id_ATM', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('banco', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='bin',
            old_name='Banco',
            new_name='banco',
        ),
    ]
