# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0007_auto_20170905_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_iniciativa',
            fields=[
                ('id_Estado_iniciativa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_iniciativa',
            fields=[
                ('id_Tipo_iniciativa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
    ]
