# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0011_auto_20170905_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id_CasoPrueba', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_prueba', models.CharField(max_length=250)),
                ('prueba', models.CharField(max_length=250)),
                ('resultado_esperado', models.CharField(max_length=45)),
                ('resultado_obtenido', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('Observaciones', models.CharField(max_length=45)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Bin')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Estado')),
                ('pestana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Pestana')),
            ],
        ),
    ]
