# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0012_casoprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
