# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0013_auto_20170910_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='producto',
            field=models.CharField(default=2, max_length=45),
            preserve_default=False,
        ),
    ]
