# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0014_bin_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoprueba',
            name='ATM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.ATM'),
        ),
    ]
