# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0017_auto_20170916_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atm',
            old_name='banco',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='atm',
            old_name='nombre',
            new_name='Modelo',
        ),
        migrations.AddField(
            model_name='atm',
            name='terminal',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
