# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0020_auto_20170917_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoprueba',
            name='fecha',
            field=models.CharField(max_length=250),
        ),
    ]
