# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0021_auto_20170917_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoprueba',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
