# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0024_auto_20170917_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoprueba',
            name='resultado_esperado',
            field=models.CharField(max_length=500),
        ),
    ]
