# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0025_auto_20170917_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoprueba',
            name='trx',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
