# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuar',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuar',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Usuar',
        ),
    ]
