# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20171014_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
