# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administrador', '0026_casoprueba_trx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id_Iniciativa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('cod_iniciativa', models.CharField(blank=True, max_length=15, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name=b'%d/%m/%Y')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name=b'%d/%m/%Y')),
                ('fecha_cierre_real', models.DateField(blank=True, null=True, verbose_name=b'%d/%m/%Y')),
                ('tipo_prueba', models.CharField(blank=True, max_length=250, null=True)),
                ('prueba', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_desarrollo', models.CharField(blank=True, max_length=45, null=True)),
                ('observaciones', models.CharField(max_length=45)),
                ('certificador', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('desarrollador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Desarrollador')),
                ('estado_iniciativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Estado_iniciativa')),
                ('tipo_iniciativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Tipo_iniciativa')),
            ],
        ),
    ]
