# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='estado_iniciativa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='observaciones',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
