# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0026_casoprueba_trx'),
        ('Gestor', '0002_auto_20170926_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='pestanas',
            field=models.ManyToManyField(blank=True, null=True, to='Administrador.Pestana'),
        ),
    ]
