# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0003_iniciativa_pestanas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciativa',
            name='certificador',
        ),
        migrations.RemoveField(
            model_name='iniciativa',
            name='pestanas',
        ),
    ]
