# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administrador', '0026_casoprueba_trx'),
        ('Gestor', '0004_auto_20170930_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('certificador', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('iniciativa', models.ManyToManyField(blank=True, null=True, to='Gestor.Iniciativa')),
                ('pestanas', models.ManyToManyField(blank=True, null=True, to='Administrador.Pestana')),
            ],
        ),
    ]
