# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0005_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='certificador',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='iniciativa',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='pestanas',
        ),
        migrations.DeleteModel(
            name='asignacion',
        ),
    ]
