# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0007_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='certificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Certificadores'),
        ),
    ]
