# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0007_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='certificador',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
