from __future__ import absolute_import
from django.conf.urls import url, include
from apps.Administrador.views import index_administrador, bin_view, pestana_view, ATM_view, Estado_view, Estado_iniciativa_view, Tipo_iniciativa_view, Desarrollador_view, Perfil_view, Usuario_view, CPM_view, bin_list, bin_edit, bin_delete, atm_list, atm_edit, atm_delete, pestana_list, pestana_edit, pestana_delete, estado_list, estado_edit, estado_delete, caso_list, caso_edit, caso_delete, tipo_list, tipo_edit, tipo_delete, estadoi_list, estadoi_edit, estadoi_delete, usuario_list, usuario_edit, usuario_delete, desarrollador_list, desarrollador_edit, desarrollador_delete, perfil_list, perfil_edit, perfil_delete, binlist, perfillist, pestanalist

urlpatterns = [
    url(r'^$', index_administrador, name = 'index_administrador'),
    url(r'^nuevo_bin$', bin_view, name = 'bin_crear'),
    url(r'^nueva_pestana$', pestana_view, name = 'pestana_crear'),
    url(r'^nuevo_atm$', ATM_view, name = 'ATM_crear'),
    url(r'^nuevo_estado$', Estado_view, name = 'Estado_crear'),
    url(r'^nuevo_estadoi$', Estado_iniciativa_view, name = 'Estadoi_crear'),
    url(r'^nuevo_tipoi$', Tipo_iniciativa_view, name = 'Tipoi_crear'),
    url(r'^nuevo_desarrollador$', Desarrollador_view, name = 'Desarrollador_crear'),
    url(r'^nuevo_perfil$', Perfil_view, name = 'Perfil_crear'),
    url(r'^nuevo_usuario$', Usuario_view, name = 'Usuario_crear'),
    url(r'^nuevo_cpm$', CPM_view, name = 'CPM_crear'),
    url(r'^listar_bin', binlist.as_view(), name = 'Bin_listar'),
    url(r'^editar/(?P<id_Bin>\d+)/$', bin_edit, name = 'Bin_editar'),
    url(r'^eliminar/(?P<id_Bin>\d+)/$', bin_delete, name = 'Bin_eliminar'),
    url(r'^listar_atm$', atm_list, name = 'Atm_listar'),
    url(r'^editar1/(?P<id_ATM>\d+)/$', atm_edit, name = 'Atm_editar'),
    url(r'^eliminar1/(?P<id_ATM>\d+)/$', atm_delete, name = 'Atm_eliminar'),
    url(r'^listar_pestana', pestanalist.as_view(), name = 'Pestana_listar'),
    url(r'^editar2/(?P<id_pestana>\d+)/$', pestana_edit, name = 'Pestana_editar'),
    url(r'^eliminar2/(?P<id_pestana>\d+)/$', pestana_delete, name = 'Pestana_eliminar'),
    url(r'^listar_estado$', estado_list, name = 'Estado_listar'),
    url(r'^editar3/(?P<id_Estado>\d+)/$', estado_edit, name = 'Estado_editar'),
    url(r'^eliminar3/(?P<id_Estado>\d+)/$', estado_delete, name = 'Estado_eliminar'),
    url(r'^listar_caso$', caso_list, name = 'Caso_listar'),
    url(r'^editar4/(?P<id_CasoPrueba>\d+)/$', caso_edit, name = 'Caso_editar'),
    url(r'^eliminar4/(?P<id_CasoPrueba>\d+)/$', caso_delete, name = 'Caso_eliminar'),
    url(r'^listar_tipo$', tipo_list, name = 'Tipo_listar'),
    url(r'^editar5/(?P<id_Tipo_iniciativa>\d+)/$', tipo_edit, name = 'Tipo_editar'),
    url(r'^eliminar5/(?P<id_Tipo_iniciativa>\d+)/$', tipo_delete, name = 'Tipo_eliminar'),
    url(r'^listar_estadoi$', estadoi_list, name = 'Estadoi_listar'),
    url(r'^editar6/(?P<id_Estado_iniciativa>\d+)/$', estadoi_edit, name = 'Estadoi_editar'),
    url(r'^eliminar6/(?P<id_Estado_iniciativa>\d+)/$', estadoi_delete, name = 'Estadoi_eliminar'),
    url(r'^listar_usuario$', usuario_list, name = 'Usuario_listar'),
    url(r'^editar7/(?P<id_Usuario>\d+)/$', usuario_edit, name = 'Usuario_editar'),
    url(r'^eliminar7/(?P<id_Usuario>\d+)/$', usuario_delete, name = 'Usuario_eliminar'),
    url(r'^listar_desarrollador$', desarrollador_list, name = 'Desarrollador_listar'),
    url(r'^editar8/(?P<id_Desarrollador>\d+)/$', desarrollador_edit, name = 'Desarrollador_editar'),
    url(r'^eliminar8/(?P<id_Desarrollador>\d+)/$', desarrollador_delete, name = 'Desarrollador_eliminar'),
    url(r'^listar_perfil', perfillist.as_view(), name = 'Perfil_listar'),
    url(r'^editar9/(?P<id_Perfil>\d+)/$', perfil_edit, name = 'Perfil_editar'),
    url(r'^eliminar9/(?P<id_Perfil>\d+)/$', perfil_delete, name = 'Perfil_eliminar'),

]
